"""
Regenerate RobotControl.ico and the browser favicon from the SVG masters in this folder.

    uv run --locked python build_scripts/icon/make_icon.py

Run it after changing the art and commit the outputs. Pillow cannot rasterise SVG, so the
frames are rendered by the frontend's Playwright driving Microsoft Edge (as the browser
checks do); that needs `npm --prefix frontend ci`. Packaging needs neither: it only reads
the committed RobotControl.ico.
"""

import base64
import io
import json
import subprocess
from pathlib import Path

from PIL import Image

ICON_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = ICON_DIR.parent.parent
ICO = ICON_DIR / "RobotControl.ico"
FAVICON = PROJECT_ROOT / "frontend" / "src" / "favicon.svg"
FAVICON_ART = "icon-small.svg"

# Small sizes use the simplified art: the detailed plate wells blur into noise below 64 px.
# At 16 and 24 px the 32-unit art falls on half pixels, so those sizes have hand-snapped copies.
FRAME_ART = {
    16: "icon-16.svg", 20: "icon-small.svg", 24: "icon-24.svg",
    32: "icon-small.svg", 40: "icon-small.svg", 48: "icon-small.svg",
    64: "icon-detailed.svg", 128: "icon-detailed.svg", 256: "icon-detailed.svg",
}

# Reads [{svg, size}] on stdin, prints base64 PNGs with a transparent background.
RENDER_JS = r"""
const { chromium } = require('@playwright/test');
(async () => {
  const jobs = JSON.parse(require('fs').readFileSync(0, 'utf8'));
  const browser = await chromium.launch({ channel: 'msedge' });
  const page = await browser.newPage({ deviceScaleFactor: 1 });
  const out = [];
  for (const { svg, size } of jobs) {
    await page.setViewportSize({ width: size, height: size });
    const src = 'data:image/svg+xml;base64,' + Buffer.from(svg).toString('base64');
    await page.setContent(`<style>html,body{margin:0;background:transparent}img{display:block}</style>`
      + `<img src="${src}" width="${size}" height="${size}">`);
    await page.locator('img').evaluate(img => img.decode());
    out.push((await page.screenshot({ omitBackground: true })).toString('base64'));
  }
  await browser.close();
  process.stdout.write(JSON.stringify(out));
})().catch(error => { console.error(error); process.exit(1); });
"""


def render(jobs: list[dict]) -> list[Image.Image]:
    result = subprocess.run(["node", "-e", RENDER_JS], cwd=PROJECT_ROOT / "frontend", input=json.dumps(jobs),
                            capture_output=True, text=True, encoding="utf-8", check=True)
    return [Image.open(io.BytesIO(base64.b64decode(png))).convert("RGBA") for png in json.loads(result.stdout)]


def main() -> None:
    jobs = [{"svg": (ICON_DIR / art).read_text(encoding="utf-8"), "size": size} for size, art in FRAME_ART.items()]
    frames = render(jobs)
    for size, frame in zip(FRAME_ART, frames):
        assert frame.size == (size, size), f"{size}px frame rendered as {frame.size}"
    # Pillow resamples the largest image for any size it is not given; every size is given here.
    largest = frames[-1]
    largest.save(ICO, format="ICO", sizes=[frame.size for frame in frames], append_images=frames[:-1])
    with Image.open(ICO) as written:
        assert sorted(written.info["sizes"]) == sorted(frame.size for frame in frames), written.info["sizes"]
    print(f"Wrote {ICO.relative_to(PROJECT_ROOT)} ({', '.join(str(s) for s in FRAME_ART)} px)")

    art = (ICON_DIR / FAVICON_ART).read_text(encoding="utf-8").strip()
    FAVICON.write_text(f"<!-- Generated by build_scripts/icon/make_icon.py from {FAVICON_ART}; edit the master. -->\n"
                       f"{art}\n", encoding="utf-8")
    print(f"Wrote {FAVICON.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
